FROM pgvector/pgvector:pg14
COPY pg_hba.conf /tmp/pg_hba.conf
COPY docker-entrypoint-initdb.d/99-trust-all.sh /docker-entrypoint-initdb.d/99-trust-all.sh
RUN chmod +x /docker-entrypoint-initdb.d/99-trust-all.sh
